services:
  graphhopper:
    image: israelhikingmap/graphhopper:latest
    container_name: graphhopper
    ports:
      - "8989:8989"
    environment:
      - JAVA_OPTS=-Xmx6g -Xms6g
    volumes:
      - ./src/main/resources/graphhopper/data:/data
      - ./src/main/resources/graphhopper/config.yml:/opt/graphhopper/config.yml
    command: >
      --config /opt/graphhopper/config.yml
      --host 0.0.0.0
    # restart: always